# Path to the directory where the model files are present.
string model_path
# action=1 (For upload the model) & action=0 for deleting the model.
int32  action
---
# Details about the action execution status.
string status
