# Calibration type (steering/speed)
int32 cal_type
---
# Maximum PWM value as per the caibration file.
int32 max
# Mid PWM value as per the caibration file.
int32 mid
# Minimum PWM value as per the caibration file.
int32 min
# Polarity value as per the caibration file.
int32 polarity
# Error flag indicating successful/failed service call.
int32 error