# Name of the model folder where the model.pb file is present.
string model_name
# Identifiers for the sensors used by the model during training.
int32[] model_metadata_sensors
# Identifier for the training algorithm used by the model during training.
int8 training_algorithm
# Identifier for the action space type used by the model during training.
int8 action_space_type
# "BGR" / "RGB" image format required to be set to run optimizer.
string img_format
# Width of the input image.
int32 width
# Height of the input image.
int32 height
# Number of channels of the input image.
int32 num_channels
# Number of distance values the model expects for LiDAR head.
int32 lidar_channels
# Identifier for the machine learning platform type used by the model during training.
# (Tensorflow, mxnet)
int32 platform
# Identifier of a particular type of inference (Ex: reinforcement learning).
int8 task_type
# Identifier of a particular type of preprocessing (Ex: grey scale + resize).
int8 pre_process_type
---
# Error flag indicating successful/failed service call.
int32 error