# File/folder to be added to the watchlist.
string file_name
# Callback name that is will be triggered if the file/folder is found.
string callback_name
# If set to True, notification will be sent for the callback only if the
# particular file is found.
# Else will be triggered irrespectively to indicate connection of USB drive.
bool verify_name_exists
---
# Error flag indicating successful/failed service call.
int32 error