# Calibration type (steering/speed)
int32 cal_type
# Maximum PWM value to be set as caibration.
int32 max
# Mid PWM value to be set as caibration.
int32 mid
# Minimum PWM value to be set as caibration.
int32 min
# Polarity value to be set as caibration.
int32 polarity
---
# Error flag indicating successful/failed service call.
int32 error