# Tail LED PWM value for RED channel.
int32 red
# Tail LED PWM value for BLUE channel.
int32 green
# Tail LED PWM value for GREEN channel.
int32 blue
---
# Error flag indicating successful/failed service call.
int32 error
